### ISSUE TITLE
cleaning up unused placeholder rules.

### ISSUE THREAD

**Issue by jithin1987** [travco/postcss-extend#11]
This plugins removes a rule from generated css file only if the rule is used. Is there a way to strip off all placeholders? My generated css files has plenty of `%` placeholders lingering around.

**Comment by travco** [comment]
I'll look into it, I can certainly see why you wouldn't want them hanging around. Have you tried using a linter after using extend? To be frankly honest I don't know if it would clean them out as `%` is still prototype syntax but since it doesn't refer to anything it might catch them

**Comment by jithin1987** [comment]
I have not tried using linters with postcss. Is there one which you recommend?

**Comment by travco** [comment]
I'd say stylelint for modularity (though there are others: https://github.com/postcss/postcss#linters)

That being said (now that I've gotten sleep and can think straight) the linter is almost guaranteed to not help with all the silent `%` placeholders, which I am currently working on fixing.

**Comment by travco** [comment]
Cleaning of placeholders to be fixed at the same time as #10
