### ISSUE TITLE
Does not work in a nested class name

### ISSUE THREAD

**Issue by fsy0718** [travco/postcss-extend#14]
```
.extend {
  color: red;
}
.test{
  .tip {
    @extend .extend;
  }
}
```

expect output link this
```
.extend,.test .tip{
  color: red;
}
```
actually output link this
```
.extend, .tip {
    color: red;
}
.test{
}
```

**Comment by timkelty** [comment]
@fsy0718 are you including `postcss-nested` before or after `postcss-extend`?

**Comment by fsy0718** [comment]
It seems to be the order of the two plug-in I made a mistake, and now the output is normal, thank you

**Comment by travco** [comment]
Thanks for jumping on that @timkelty .
