### ISSUE TITLE
False warning?

### ISSUE THREAD

**Issue by zslabs** [travco/postcss-extend#19]
If I have the following:

    %hook-Button {}

    .Button {
      border: 1px solid black;
      @extend %hook-Button;
    }

    %hook-Button {
      background: green;
    }

It's still saying `@extend is being used in an anti-pattern (extending things not yet defined). This is your first and final warning`.

I'd think that since I'm "extending and extend" that this should work fine. The compiled CSS looks good, but the warning seems off.

**Comment by travco** [comment]
It's a naive lookup to see if what is being extended is further down in the CSS than the `@extend` statment. As per the answer to issue #15 , it's inching toward the chopping block.
