### ISSUE TITLE
Cannot extend from nested placeholder

### ISSUE THREAD

**Issue by redaxmedia** [travco/postcss-extend#23]
Hello,

I have a set of <code>%rs-icon-xxx</code> placeholders generated via grunt-webfont that need to be extended within nesting. It fails with postcss-nesting and postcss-nested. There were a couple of related issues on multiple sub-projects of PostCSS but it was never solved.

Placeholder:
<pre>
%rs-icon-chevron-right
{
	content: '\3009';
	font-family: var(--rs-font-icon);
}</pre>

Nesting:
<pre>
.rs-list-breadcrumb
{
	& .rs-item-divider
	{
		&:before
		{
			@extend %rs-icon-chevron-right;
		}
	}
}
</pre>

Generated output:

<pre>
&:before
{
	content: '\3009';
	font-family: 'icon default';
}</pre>

Wanted output:
<pre>
.rs-list-breadcrumb .rs-item-divider:before
{
	content: '\3009';
	font-family: 'icon default';
}</pre>

Config:
<pre>
require('postcss-custom-properties'),
require('postcss-custom-media'),
require('postcss-custom-selectors'),
require('postcss-extend'),
require('postcss-nesting'),
require('postcss-color-gray'),
require('postcss-color-function'),
require('autoprefixer')(
{
	browsers: 'last 2 versions',
	cascade: false
})</pre>

Sourecode:
https://github.com/redaxmedia/redaxscript/blob/3.0.0/templates/default/assets/styles/_icon.css
https://github.com/redaxmedia/redaxscript/blob/3.0.0/templates/default/assets/styles/breadcrumb.css

Gruntfile:
https://github.com/redaxmedia/redaxscript/blob/3.0.0/gruntfile.js

Thank you

**Comment by ai** [comment]
Could you try put `postcss-extend` after `postcss-nested`. Also I highly recommend to use [PreCSS](https://github.com/jonathantneal/precss), because it has predefined plugins list with right order (on PostCSS website and README.md we promote only it)

**Comment by redaxmedia** [comment]
I tried all kind of order but this changed nothing. I try the package later. Maybe you find some time to create your own testcase to validate the issue.

**Comment by redaxmedia** [comment]
The ordering fixed the issue, maybe it was too late yesterday - fixed it today within minutes... :-)

<pre>
require('postcss-nesting'),
require('postcss-extend'),
</pre>
