### ISSUE TITLE
Is it possible to extend classes from the external file?

### ISSUE THREAD

**Issue by lavezzi1** [travco/postcss-extend#26]
Tried this but doesn't works: 

```
@import ‘library/link/style.css';

.super-duper-link {
    @extend .link;
}
```

Is it possible or not with postcss?

**Comment by travco** [comment]
Should be possible, 
Have you tried putting postcss-import before postcss-extend in your configuration?

**Comment by lavezzi1** [comment]
This order fixed problem:
```
        require('postcss-import')({
            addDependencyTo: webpack
        }),
        require('postcss-nested')(),
        require('postcss-extend')(),
```

**Comment by travco** [comment]
@lavezzi1 Is there anything else or can we consider the issue closed?

(General etiquette to have the opener of the issue close it)

**Comment by lavezzi1** [comment]
Nope! Thanks.
