### ISSUE TITLE
Extending defined selector throws anti-pattern warning

### ISSUE THREAD

**Issue by timkelty** [travco/postcss-extend#3]
Using code from README:

```
.potato {
  color: white;
  outline: brown;
  font-family: sans-serif;
}

@media (width > 600px) {
  .spud {
    @extend .potato;
  }
}
```

This throws the anti-pattern warning, though the output is what you would want. Seems like it shouldn't throw the error if the selector is defined in the parent/root context.

Also - errors are formatted with a `[postcss-simple-extend]' instead of just `[postcss-extend]`

**Comment by kswedberg** [comment]
Pretty sure we're getting the `[postcss-simple-extend]` warnings because of this:
https://github.com/travco/postcss-extend/blob/master/index.js#L6

Anything keeping you from changing that to "postcss-extend", @travco ?

**Comment by travco** [comment]
Negative, It'll be out of the codebase by the end of today. Frankly I'm surprised it didn't cause more issues.

**Comment by travco** [comment]
Fixed via: https://github.com/travco/postcss-extend/commit/b4010ab4d96b4e107ab3a510d6405101aecb859b Bad plugin name (still facepalming over this) sorted, and false-positive antipattern warnings fixed with tests added.

**Comment by kswedberg** [comment]
thanks, @travco !
