### ISSUE TITLE
Using one extends.css

### ISSUE THREAD

**Issue by canvaskisa** [travco/postcss-extend#4]
Thanks for that cool plugin, but i've got a question: i've got several .css files & one extends.css file, so i wanna include all extends in my other css, `@import 'extends';` throws an error `<extend-class> has not been defined, so it cannot be extended`, any options about that?

**Comment by travco** [comment]
Sorry for the somewhat late response, have you checked your PostCSS configuration? If you want to import things and them extend them, postcss-import needs to be run before postcss-extend.

(Also, if you're not using [postcss-import](https://github.com/postcss/postcss-import) extend does not do the legwork of also handling the `@import`)

**Comment by canvaskisa** [comment]
@travco I wasn't using postcss-import, cause of webpack, but including it in postcss transformers list made everything fine. Thanks!
