### ISSUE TITLE
Alias for @extend

### ISSUE THREAD

**Issue by niksy** [travco/postcss-extend#7]
Is it possible to have alias for `@extend` just like original postcss-simple-extend (https://github.com/davidtheclark/postcss-simple-extend/blob/master/index.js#L9)?

**Comment by travco** [comment]
Yep, that functionality was kept in completely - infact it's almost on the same line. For the sake of simplicity (and not having a separate config file) it's right at the top of the script
https://github.com/travco/postcss-extend/blob/master/index.js#L10
